#!/bin/csh
#PBS -l walltime=00:15:00
#PBS -l mppwidth=1
#PBS -l mppdepth=
#PBS -q debug
#PBS -N stream
#PBS -j oe
#PBS -o job.out

cd $PBS_O_WORKDIR

setenv OMP_NUM_THREADS 
aprun -n1  -d  ./stream_c.exe 

