#!/usr/bin/python

import subprocess
f = open('netperf.csv', 'a')

for run in range(10):
	test = subprocess.Popen(["netperf", "-H", "206.12.154.112", "-P", "0", "-v", "0"], stdout=subprocess.PIPE)

	out, err = test.communicate()

	f.write(out)

f.close()
